### ISSUE TITLE
runtime error: cannot fit 'int' into an index-sized integer

### ISSUE THREAD

**Issue by yuedajiong** [WU-CVGL/MVControl-threestudio#3]
File "/opt/anaconda3/envs/v3d/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 3682, in _pad
    encoded_inputs["attention_mask"] = encoded_inputs["attention_mask"] + [0] * difference
OverflowError: cannot fit 'int' into an index-sized integer

**Comment by lizhiqi49** [comment]
Where does this error occur? Could you please provide me the complete error message?

**Comment by yuedajiong** [comment]
可能我机器GPU比较老，或者版本完全一致。 
请忽略或者关闭，这不是主要问题。
