### ISSUE TITLE
Confusion about input image types.

### ISSUE THREAD

**Issue by yuedajiong** [WU-CVGL/MVControl-threestudio#4]
个人感觉：
    照片(rgb,rgba): 90%，草图(手工简单绘制): 10%，这两种是比较自然的输入形态。

   为什么要将depth(难道是3D sensor)，normal，canny, scribble这种作为输入呢？

Thanks

**Comment by yuedajiong** [comment]
如果将“彩图”处理为“深度”等，丢失了大量的信息，作为条件，得到的大概率就是其他的类别了。

当然，还有可能就是训练集数据多样性不够，只能往见过的类别上靠。  多样性先验：现在一是objavese等，二是image2video，这两个见多识广。


![image](https://github.com/WU-CVGL/MVControl-threestudio/assets/52232153/574e5b43-79cf-4aef-a37b-37c8062f657b)

![image](https://github.com/WU-CVGL/MVControl-threestudio/assets/52232153/004867e9-78db-4407-a249-778ced8ab76d)

**Comment by lizhiqi49** [comment]
Thanks for your question. Actually our work is the multi-view (MV)/3D scenerio of 2D ControlNet, which fills the gap between text- and image-to-MV/3D. In most of this scenerio, the user may want to generate a series of diverse assets of the same shape with an origin image (object) but of different content (textual description). And the shape is controlled by its corresponding depth map, canny edge, normal map, or scribble, which are easy to extract using pretrained models.

**Comment by yuedajiong** [comment]
thanks, got it.
trend to 'diverse' generate.
but not 'copy-like' reconstrction.
thanks again.
